export const MENU_SWITCH = 'MENU_SWITCH'
export const ME_SET = 'ME_SET'
export const TRACKS_SET = 'TRACKS_SET'
export const TRACK_PLAY = 'TRACK_PLAY'
export const TRACK_NEXT = 'TRACK_NEXT'
export const TRACK_PREV = 'TRACK_PREV'